/* Lógico_B: */

CREATE TABLE MUSICO (
    CODMUSICO INTEIRO PRIMARY KEY,
    NOMEMUSICO TEXTO(100),
    FK_ESPECIALIDADE_ESPECIALIDADE_PK INTEIRO
);

CREATE TABLE INSTRUMENTOS (
    CODINSTRUMENTO INTEIRO PRIMARY KEY,
    NOME TEXTO(100),
    FK_MARCA_MARCA_PK INTEIRO,
    VALOR REAL
);

CREATE TABLE ESPECIALIDADE (
    ESPECIALIDADE_PK INTEIRO NOT NULL PRIMARY KEY,
    ESPECIALIDADE TEXTO(50)
);

CREATE TABLE MARCA (
    MARCA_PK INTEIRO NOT NULL PRIMARY KEY,
    MARCA TEXTO(50)
);

CREATE TABLE TOCA (
    FK_INSTRUMENTOS_CODINSTRUMENTO INTEIRO,
    FK_MUSICO_CODMUSICO INTEIRO
);
 
ALTER TABLE MUSICO ADD CONSTRAINT FK_MUSICO_2
    FOREIGN KEY (FK_ESPECIALIDADE_ESPECIALIDADE_PK)
    REFERENCES ESPECIALIDADE (ESPECIALIDADE_PK)
    ON DELETE NO ACTION;
 
ALTER TABLE INSTRUMENTOS ADD CONSTRAINT FK_INSTRUMENTOS_2
    FOREIGN KEY (FK_MARCA_MARCA_PK)
    REFERENCES MARCA (MARCA_PK)
    ON DELETE NO ACTION;
 
ALTER TABLE TOCA ADD CONSTRAINT FK_TOCA_1
    FOREIGN KEY (FK_INSTRUMENTOS_CODINSTRUMENTO)
    REFERENCES INSTRUMENTOS (CODINSTRUMENTO)
    ON DELETE RESTRICT;
 
ALTER TABLE TOCA ADD CONSTRAINT FK_TOCA_2
    FOREIGN KEY (FK_MUSICO_CODMUSICO)
    REFERENCES MUSICO (CODMUSICO)
    ON DELETE SET NULL;